export const LOGIN_REGISTER_REQUEST = 'LOGIN_REGISTER_REQUEST';
export const LOGIN_REGISTER_REQUEST_SUCCESS = 'LOGIN_REGISTER_REQUEST_SUCCESS';
export const LOGIN_REGISTER_REQUEST_FAILED = 'LOGIN_REGISTER_REQUEST_FAILED';
export const LOGOUT = 'LOGOUT';

export const ADD_MOVIVES = 'ADD_MOVIVES';

export const VOTE_MOVIE_REQUEST = 'VOTE_MOVIE_REQUEST';
export const VOTE_MOVIE_REQUEST_SUCCESS = 'VOTE_MOVIE_REQUEST_SUCCESS';
export const VOTE_MOVIE_REQUEST_FAILED = 'VOTE_MOVIE_REQUEST_FAILED';
