export const LOGIN_REGISTER_REQUEST = 'LOGIN_REGISTER_REQUEST';
export const LOGIN_REGISTER_REQUEST_SUCCESS = 'LOGIN_REGISTER_REQUEST_SUCCESS';
export const LOGIN_REGISTER_REQUEST_FAILED = 'LOGIN_REGISTER_REQUEST_FAILED';
export const LOGOUT = 'LOGOUT';
